### ISSUE TITLE
Should IRSTLM stop if no <s> in text corpus?

### ISSUE THREAD

**Issue by colbec** [irstlm-team/irstlm#3] opened 2015-12-24 09:32 UTC
When creating an LM for Julius to process into a binary version with mkbingram, it seems to be important to include in the text corpus the silence markers. IRSTLM will quite happily process a model in both iARPA and ARPA without them, but later mkbingram will fail if silences are absent from the corpus (https://github.com/julius-speech/julius/issues/15) and the resulting LM from IRSTLM. The question is whether the standard is for silences to be included in the corpus (in which case a check is missing in the language model generator) or optional (in which case the issue can be dealt with by mkbingram)?

**Comment by nicolabertoldi** [comment] 2015-12-24 09:43
I am not sure I understood you quetion

First of all, 
symbols <s> and </s> are used in IRSTLM to identify start and end of a sentence
and to avoid that cross-sentence ngrams will included in the LM.


Assuming you have these two sentences in the training data
prime minister of japan
plight of street children

in a 4-gram LM  trained on that,  the following cross-sentence ngrams will be included (together with the others
minister of japan plight
of japan plight of
japan plight of street


instead if you have the start and end symbols
<s> prime minister of japan </s>
<s> plight of street children </s>

the previous n-grams will not be included
But on the other side the following ngrams wil be included
minister of japan </s>
of street children </s>


Hope this helps
if you need more clarification, please do not hesitate to contact me again with detailed requests

best regards,
Nicola

**Comment by colbec** [comment] 2015-12-24 10:13
Right, I understand your explanation. The issue is that Julius mkbingram will understand an IRSTLM model and convert to binary **if** explicit silence markers appear in the corpus, but will not if they are absent and IRSTLM inserts defaults, which I assume it will do if there are no explicit markers.
Given a corpus :
>ONE TWO
>THREE FOUR

I'm guessing that IRSTLM will assume a \<s> before ONE and a \</s> after FOUR and build these into the model; is this correct? For some reason mkbingram much prefers the silence markers to be explicit and not defaulted in, so to speak.
It's strange, about a year ago I think I was able to use a corpus without explicit markers without a problem, but now they seem to be required. It's not a big problem, now that I know the markers should be explicit all flows smoothly. Thanks for listening.

**Comment by nicolabertoldi** [comment] 2016-01-12 17:57
IRSTLM adds a sequence of <s> symbols at the beginning of the corpus only (and not for each sentence) to keep the internal data structure well-formed
IRSTLM does not add any other symbols, but those explained above.

in other words, IRSTLM works as the input was 
<s> ONE TWO
THREE FOUR

Hence, you have to add  the end symbol explicitely at the end of all lines  or at the end of the entire input at your convenience.

**Closed** 2016-05-04 08:55 UTC

**Comment by xsway** [comment] 2017-10-25 10:07
Hi, I ran into a similar problem.

My corpus doesn't have \<s\> and \</s\> by design.

But after getting an IRSTLM model \<s\> gets introduced (once) into the training data. However, it's not at the beginning of the training file as you suggested, but at the end. 

The problem is that only the following ngrams with \<s\> get generated:
-6.98116	<eos> \<s\>	-0.107586
-7.15098	. <eos> \<s\>	-0.060487
-6.13303	) . <eos> \<s\>	-0.032553

There is no \<s\> unigram! This breaks things when trying to use this LM.
